{
	"Target": {
		"EntitySet": "MyEquipments",
		"Service": "/SAPAssetManager/Services/AssetManager.service",
		"EditLink": "{@odata.readLink}"
	},
	"OnSuccess": "/SAPAssetManager/Rules/Common/DeleteEntityOnSuccess.js",
	"OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/DeleteEntityFailureMessage.action",
	"_Type": "Action.Type.OfflineOData.UndoPendingChanges"
}