{
	"_Type": "Action.Type.RestService.SendRequest",
	"Target": {
		"Service": "/SAPAssetManager/Services/ESRIRest.service",
		"Path": "/SAPAssetManager/Rules/ESRI/GetRefreshTokenPath.js",
		"RequestProperties": {
			"Method": "GET"
		}
	}
}