{
    "_Type" : "Action.Type.Filter",
    "PageToOpen" : "/SAPAssetManager/Pages/FunctionalLocation/FunctionalLocationFilter.page",
    "Filterable" : "#Page:FunctionalLocationListViewPage/#Control:SectionedTable",
    "ActionResult": {
        "_Name": "filterResult"
    }
}